### ISSUE TITLE
Add Links From InfoBox To Tables

### ISSUE THREAD

**Issue by opticyclic** [dali110/react-material-admin#3]
Add links to the InfoBox so you can click from the Total Profit on the Dashboard to the Data Table for instance

**Comment by hanyuei** [comment]
@opticyclic 

hi, thanks for your feedback on this.

if you want to link to some page when clicking any infoBox , you could simply wrap that Infobox with a `Link` component.

```js
<Link key={some-key} to={some-page-path}>
   <InfoBox .../> 
</Link>
```


` (also you could add some css or button component for customizing the animation when clicking if you want)`

**Comment by opticyclic** [comment]
Thanks for the tip. I have implemented that in my version.

I thought it might be nice to include it in your template to make the demo seem more functional.

**Comment by hanyuei** [comment]
i see, 
i may add it when i have free time.

@opticyclic if you have time and want to contribute any code to the repo, please feel free to do pull request.

**Comment by zhuang17** [comment]
fixed in https://github.com/zhuang17/react-material-admin/commit/593c567e039c22a0596f0cb72940296ccad15ecf

**Comment by hanyuei** [comment]
fixed in https://github.com/zhuang17/react-material-admin/commit/593c567e039c22a0596f0cb72940296ccad15ecf
